version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=FastDate
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=TESTED_DB
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=postgres_test
    ports:
      - "5434:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
